site_name: TechDocs
repo_url: https://github.com/igorbraga13/
site_url: https://igorbraga13.github.io/modeling_guide/

nav: 
  - Modeling Guideline: 
    - 📝 Overview: A_modeling_guideline/A_overview.md
    - ❓ Problem Understanding: A_modeling_guideline/B_problem_understanding.md
    - 📊 Data Understanding and Preparation: A_modeling_guideline/C_data_preparation.md
    - 🔍 Exploratory Data Analysis: A_modeling_guideline/D_eda.md
    - 🛠️ Feature Engineering: A_modeling_guideline/E_feature_engineering.md
    - 🧮 Modeling and Evaluation or Model Design: A_modeling_guideline/F_model_selection.md
    - 🚀 Deployment and Operationalization: A_modeling_guideline/J_deployment.md
    - 📈 Model Monitoring and Maintenance: A_modeling_guideline/K_monitoring.md
    - ⚖️ Governance, Ethical, and Regulatory Considerations: A_modeling_guideline/L_governance.md
    - 🧰 Tools, Technologies, and Best Practices: A_modeling_guideline/M_tools.md
    - 📚 Appendix: A_modeling_guideline/N_appendix.md
    - Legado: A_modeling_guideline/modeling_guideline.md

  - Artifacts: 
    - 🧾 Discovery: B_artifacts/discovery.md
    - 🆗 Model Approval: B_artifacts/model_approval.md
    - 📝 Technical Documentation: B_artifacts/technical_documentation.md
  
  - Patterns:
    - Data Preparation: C_patterns/data_preparation.md
    #- Feature Engineering: feature_engineering.md
    #- Model Evaluation: model_evaluation.md
    #- Model Deployment: model_deployment.md
    #- Model Monitoring: model_monitoring.md
  
  - Statistical Concepts:
    - Accuracy: D_statistical_concepts/accuracy.md
    - ARIMA: D_statistical_concepts/arima.md
    - Bayesian Statistics: D_statistical_concepts/bayesian_statistics.md
    - Bagging: D_statistical_concepts/bagging.md
    - Boosting: D_statistical_concepts/boosting.md
    - Calibration: D_statistical_concepts/calibration.md
    - Central Limit Theorem: D_statistical_concepts/central_limit_theorem.md
    - Correlation: D_statistical_concepts/correlation.md
    - Covariance: D_statistical_concepts/covariance.md
    - Cross-Validation: D_statistical_concepts/cross_validation.md
    - Chi-Squared: D_statistical_concepts/chisq_test.md
    - Decision Trees: D_statistical_concepts/decision_trees.md
    - Design of Experiments: D_statistical_concepts/doe.md
    - Distributions: D_statistical_concepts/distributions.md
    - Elastic Net: D_statistical_concepts/elastic_net.md
    - Entropy: D_statistical_concepts/entropy.md
    - F1 Score: D_statistical_concepts/f1_score.md
    - Hellinger Distance: D_statistical_concepts/hellinger_distance.md
    - Heuristic: D_statistical_concepts/heuristic.md
    - Homogeneity: D_statistical_concepts/homogeneity.md
    - Homoscedasticity: D_statistical_concepts/homoscedasticity.md 
    - Hypothesis Testing: D_statistical_concepts/hypothesis_testing.md
    - ICE: D_statistical_concepts/ice.md
    - Information Gain: D_statistical_concepts/information_gain.md
    - Information Value: D_statistical_concepts/information_value.md
    - Jensen-Shannon Divergence: D_statistical_concepts/js_divergence.md
    - Kolmogorov-Smirnov: D_statistical_concepts/ks.md
    - Kullback-Leibler Divergence: D_statistical_concepts/kl_divergence.md
    - Kurtosis: D_statistical_concepts/kurtosis.md
    - L1 Regularization (LASSO): D_statistical_concepts/l1_regularization.md
    - L2 Regularization (Ridge): D_statistical_concepts/l2_regularization.md
    - Large Language Models (LLMs): D_statistical_concepts/llm.md
    - Levene Test: D_statistical_concepts/levene_test.md
    - LIME: D_statistical_concepts/lime.md
    - Linear Regression: D_statistical_concepts/linear_regression.md  
    - Logistic Regression: D_statistical_concepts/logistic_regression.md
    - Long Short-Term Memory (LSTM): D_statistical_concepts/lstm.md
    - Loss Function: D_statistical_concepts/loss_function.md
    - Mann-Whitney U Test: D_statistical_concepts/mann_whitney.md
    - Mean Absolute Error: D_statistical_concepts/mae.md
    - Mean Squared Error: D_statistical_concepts/mse.md
    - Multicollinearity: D_statistical_concepts/multicollinearity.md
    - Neural Networks: D_statistical_concepts/neural_networks.md
    - NLP: D_statistical_concepts/nlp.md
    - Normalization: D_statistical_concepts/normalization.md
    - Optimization: D_statistical_concepts/optimization.md
    - Outliers: D_statistical_concepts/outliers.md
    - Overfitting: D_statistical_concepts/overfitting.md
    - PCA: D_statistical_concepts/pca.md
    - PDP: D_statistical_concepts/pdp.md
    - Permutation Importance: D_statistical_concepts/permutation_importance.md
    - Precison: D_statistical_concepts/precision.md
    - Precision-Recall Curve: D_statistical_concepts/precision_recall_curve.md
    - R Squared: D_statistical_concepts/r_squared.md
    - Random Forest: D_statistical_concepts/random_forest.md
    - Recall: D_statistical_concepts/recall.md
    - Regression: D_statistical_concepts/regression.md
    - ROC AUC: D_statistical_concepts/roc_auc.md
    - Sampling: D_statistical_concepts/sampling.md  
    - Seasonality: D_statistical_concepts/seasonality.md
    - SHAP: D_statistical_concepts/shap.md
    - Skewness: D_statistical_concepts/skewness.md
    - Sobol: D_statistical_concepts/sobol.md
    - Specificity: D_statistical_concepts/specificity.md
    - Standard Deviation: D_statistical_concepts/standard_deviation.md
    - Standardization: D_statistical_concepts/standardization.md
    - Stationarity: D_statistical_concepts/stationarity.md
    - Transformers: D_statistical_concepts/transformers.md
    - Trend: D_statistical_concepts/trend.md
    - Variance: D_statistical_concepts/variance.md
    - Variance Inflation Factor: D_statistical_concepts/vif.md
    - Volatility: D_statistical_concepts/volatility.md
    - Wasserstein Distance: D_statistical_concepts/wasserstein_distance.md
    - Weight of Evidence: D_statistical_concepts/woe.md
  
  - Engineering Concepts:
    - Data Engineering: D_engineering_concepts/data_engineering.md
    - Data Quality: D_engineering_concepts/data_quality.md
    - Data Versioning: D_engineering_concepts/data_versioning.md
    - Data Warehouse: D_engineering_concepts/data_warehouse.md
    - Data Lake: D_engineering_concepts/data_lake.md
    - ETL: D_engineering_concepts/etl.md
    - Feature Store: D_engineering_concepts/feature_store.md
    - MLOps: D_engineering_concepts/mlops.md
    - Pipeline Orchestration: D_engineering_concepts/pipeline_orchestration.md

  - Glossary:
      - 💰 Bank Context:
          - Approval Rating: E_glossary/bank_context/approval_rating.md
          - BNPL: E_glossary/bank_context/bnpl.md
          - Churn: E_glossary/bank_context/churn.md
          - CAC: E_glossary/bank_context/cac.md
          - COGS: E_glossary/bank_context/cogs.md
          - Credit Cycle: E_glossary/bank_context/credit_cycle.md
          - CSI: E_glossary/bank_context/csi.md
          - CTS: E_glossary/bank_context/cts.md
          - EAD: E_glossary/bank_context/ead.md
          - ECL: E_glossary/bank_context/ecl.md
          - FGC: E_glossary/bank_context/fgc.md
          - Float: E_glossary/bank_context/float.md
          - FPD: E_glossary/bank_context/fpd.md
          - IFRS9: E_glossary/bank_context/ifrs9.md
          - Indice de Basileia: E_glossary/bank_context/indice_basileia.md
          - Is Delayed: E_glossary/bank_context/is_delayed.md
          - KPI: E_glossary/bank_context/kpi.md
          - KS: E_glossary/bank_context/ks.md
          - LGD: E_glossary/bank_context/lgd.md
          - LTV: E_glossary/bank_context/ltv.md
          - NPL: E_glossary/bank_context/npl.md
          - PD: E_glossary/bank_context/pd.md
          - PDD: E_glossary/bank_context/pdd.md
          - Receivables Assignment: E_glossary/bank_context/receivables_assignment.md
          - Revolving Credit: E_glossary/bank_context/revolving_credit.md
          - ROE: E_glossary/bank_context/roe.md
          - ROI: E_glossary/bank_context/roi.md
          - SLA: E_glossary/bank_context/sla.md
          - Stop Accrual: E_glossary/bank_context/stop_accrual.md
          - Supply Chain: E_glossary/bank_context/supply.md
          - TPV: E_glossary/bank_context/tpv.md

  - Projects:
    - Crime California (Shiny App): F_projects/crime_california.md
    - Distributions Comparison: F_projects/distributions_comparison.md
    - Fraud Detection: F_projects/fraud_detection.md
  
  - Presentations:
    - 📊 Data Science: G_presentations/data_science.md
    - 📈 Machine Learning: G_presentations/machine_learning.md
    - 🧠 Deep Learning: G_presentations/deep_learning.md
    - 🕸️ Graphs: G_presentations/graphs.md
    - 📚 Statistics: G_presentations/statistics.md
    - 🛠️ Tools and Technologies: G_presentations/tools_and_technologies.md

  - Study Notes: 
    - Teste: H_study_notes/study_notes.md
    - Optimization: 
      - Heuristical: H_study_notes/heuristical_optimization.md
      - Convex: H_study_notes/convex_optimization.md
    - Kanban: H_study_notes/kanban.md
  - Links: I_links/links.md
  
  - Articles: J_articles/articles.md
  
  - References: K_references/references.md

theme:
  name: material
  features:
    #- navigation.expand        # Menus expansíveis
    - navigation.top           # Mostra o menu de navegação no topo também
    - navigation.instant       # Navegação sem recarregar a página
  palette:
    - scheme: default         # Light mode
      primary: indigo
      accent: deep orange
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

    - scheme: slate           # Dark mode
      primary: indigo
      accent: deep orange
      toggle:
        icon: material/white-balance-sunny
        name: Switch to light mode


markdown_extensions:
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - js/mathjax-refresh.js

plugins:
  - search
  - mermaid2