site_name: TechDocs
repo_url: https://github.com/igorbraga13/
site_url: https://igorbraga13.github.io/modeling_guide/

nav: 
  - Modeling Guideline: 
    - 📝 Overview: A_modeling_guideline/A_overview.md
    - ❓ Problem Understanding: A_modeling_guideline/B_problem_understanding.md
    - 📊 Data Understanding and Preparation: A_modeling_guideline/C_data_preparation.md
    - 🔍 Exploratory Data Analysis: A_modeling_guideline/D_eda.md
    - 🛠️ Feature Engineering: A_modeling_guideline/E_feature_engineering.md
    - 🧮 Modeling and Evaluation (Model Design): A_modeling_guideline/F_model_design.md
    - 🧾 Experiment Tracking & Model Registry: A_modeling_guideline/G_experiment_tracking.md
    - 🔁 Reproducibility & Documentation: A_modeling_guideline/H_reproducibility_and_documentation.md
    - 🚀 Deployment and Operationalization: A_modeling_guideline/I_deployment.md
    - 🧪 Experimentation and Causal Evaluation: A_modeling_guideline/J_experimentation.md
    - 📈 Model Monitoring and Maintenance: A_modeling_guideline/K_monitoring.md
    - ⚖️ Governance, Ethical, and Regulatory Considerations: A_modeling_guideline/L_governance.md
    - 🧰 Tools, Technologies, and Best Practices: A_modeling_guideline/M_tools.md
    - 📚 Appendix: A_modeling_guideline/N_appendix.md
    - Legado: A_modeling_guideline/modeling_guideline.md

  - Algorithms: 
    - B_algorithms/index.md
    - 📈 Parametric Models:
      - B_algorithms/parametric_models/index.md
      - Linear Models: B_algorithms/parametric_models/linear_models.md
      - Generalized Linear Models (GLM): B_algorithms/parametric_models/glm.md
      - Discriminant Analysis: B_algorithms/parametric_models/discriminant_analysis.md
      - Generalized Additive Models (GAM): B_algorithms/parametric_models/gam.md
      - Polynomial and Spline Regression: B_algorithms/parametric_models/polynomial_spline_regression.md
      - Survival Analysis: B_algorithms/parametric_models/survival_analysis.md   
      - Validation & Evaluation Methods: B_algorithms/parametric_models/validation_evaluation.md
    - 🧮 Others Non Parametric & Kernel Methods: B_algorithms/non_parametric_models.md
    - 🌳 Tree Based Models: B_algorithms/tree_based_models.md
    - 🌲 Ensemble Methods: 
      - B_algorithms/ensemble_methods/index.md
      - 🧩 Bagging: B_algorithms/ensemble_methods/bagging.md
      - 🚀 Boosting: B_algorithms/ensemble_methods/boosting.md
      - 🪄 Stacking: B_algorithms/ensemble_methods/stacking.md
      - 🌊 Voting: B_algorithms/ensemble_methods/voting.md
      - Specialized Ensembles: B_algorithms/ensemble_methods/specialized_ensembles.md
    - 🧠 Deep Learning: B_algorithms/deep_learning.md
    - 🚀 Foundation Models: B_algorithms/foundation_models.md
    - 🧪 Causal Inference: B_algorithms/causal_inference.md
    - ⏱️ Time Series:
      - B_algorithms/time_series/index.md
      - Classical Statistical Models: B_algorithms/time_series/classical_statistical_models.md
      - Exponential Smoothing and Trend Methods: B_algorithms/time_series/exponential_smoothing_trend.md
      - State Space & Kalman-Based Models: B_algorithms/time_series/state_space_kalman.md
      - Decomposition & Regression-Based Models: B_algorithms/time_series/decomposition_regression.md
      - Machine Learning & Hybrid Approaches: B_algorithms/time_series/machine_learning_hybrid.md
      - Validation & Evaluation Methods: B_algorithms/time_series/validation_evaluation.md
    - ⏳ Survival Analysis: B_algorithms/survival_analysis.md
    - ∑ Bayesian Methods: B_algorithms/bayesian_methods.md
    - 🎮 Reinforcement Learning: B_algorithms/reinforcement_learning.md
    - 🕸️ Graph Algorithms: B_algorithms/graph_algorithms.md
    - ↘️ Dimensionality Reduction: B_algorithms/dimensionality_reduction.md
    - 🧩 Clustering: 
      - B_algorithms/clustering/index.md
      - Partition-Based: B_algorithms/clustering/partition_based.md
      - Hierarchical: B_algorithms/clustering/hierarchical.md
      - Density-Based: B_algorithms/clustering/density_based.md
      - Model-Based: B_algorithms/clustering/model_based.md
      - Graph/Prototype-Based: B_algorithms/clustering/graph_prototype_based.md
      - Validation & Evaluation Methods: B_algorithms/clustering/validation_evaluation.md
    - 🚨 Anomaly Detection: B_algorithms/anomaly_detection.md
    - 🎯 Recommendation Systems: B_algorithms/recommendation_systems.md
    - 🧬 Evolutionary Algorithms: B_algorithms/evolutionary_algorithms.md
    - 🎯 Optimization & Mathematical Programming: B_algorithms/optimization_math.md
    - ⚙️ Hybrid Models: B_algorithms/hybrid_models.md
    - Legado: B_algorithms/algorithms.md

  - Artifacts: 
    - 🧾 Discovery: C_artifacts/discovery.md
    - 🆗 Model Approval: C_artifacts/model_approval.md
    - 📝 Technical Documentation: C_artifacts/technical_documentation.md
  
  - Patterns:
    - Data Preparation: D_patterns/data_preparation.md
    #- Feature Engineering: feature_engineering.md
    #- Model Evaluation: model_evaluation.md
    #- Model Deployment: model_deployment.md
    #- Model Monitoring: model_monitoring.md
  
  - Statistical Concepts:
    - Accuracy: E_statistical_concepts/accuracy.md
    - ARIMA: E_statistical_concepts/arima.md
    - AUC: E_statistical_concepts/auc.md
    - Bayesian Statistics: E_statistical_concepts/bayesian_statistics.md
    - Bagging: E_statistical_concepts/bagging.md
    - Boosting: E_statistical_concepts/boosting.md
    - Calibration: E_statistical_concepts/calibration.md
    - Central Limit Theorem: E_statistical_concepts/central_limit_theorem.md
    - Correlation: E_statistical_concepts/correlation.md
    - Covariance: E_statistical_concepts/covariance.md
    - Cross-Validation: E_statistical_concepts/cross_validation.md
    - Chi-Squared: E_statistical_concepts/chisq_test.md
    - Confusion Matrix: E_statistical_concepts/confusion_matrix.md
    - Convolutional Neural Networks (CNN): E_statistical_concepts/cnn.md
    - Decision Trees: E_statistical_concepts/decision_trees.md
    - Design of Experiments: E_statistical_concepts/doe.md
    - Distributions: E_statistical_concepts/distributions.md
    - Elastic Net: E_statistical_concepts/elastic_net.md
    - Entropy: E_statistical_concepts/entropy.md
    - F1 Score: E_statistical_concepts/f1_score.md
    - Gini: E_statistical_concepts/gini.md
    - Graph Neural Networks: E_statistical_concepts/gnn.md
    - Hellinger Distance: E_statistical_concepts/hellinger_distance.md
    - Heuristic: E_statistical_concepts/heuristic.md
    - Homogeneity: E_statistical_concepts/homogeneity.md
    - Homoscedasticity: E_statistical_concepts/homoscedasticity.md 
    - Hypothesis Testing: E_statistical_concepts/hypothesis_testing.md
    - ICE: E_statistical_concepts/ice.md
    - Information Gain: E_statistical_concepts/information_gain.md
    - Information Value: E_statistical_concepts/information_value.md
    - Isolation Forest: E_statistical_concepts/isolation_forest.md
    - Jensen-Shannon Divergence: E_statistical_concepts/js_divergence.md
    - Kolmogorov-Smirnov (KS): E_statistical_concepts/ks.md
    - Kullback-Leibler Divergence: E_statistical_concepts/kl_divergence.md
    - Kurtosis: E_statistical_concepts/kurtosis.md
    - L1 Regularization (LASSO): E_statistical_concepts/l1_regularization.md
    - L2 Regularization (Ridge): E_statistical_concepts/l2_regularization.md
    - Large Language Models (LLMs): E_statistical_concepts/llm.md
    - Levene Test: E_statistical_concepts/levene_test.md
    - LIME: E_statistical_concepts/lime.md
    - Linear Regression: E_statistical_concepts/linear_regression.md  
    - Logistic Regression: E_statistical_concepts/logistic_regression.md
    - Long Short-Term Memory (LSTM): E_statistical_concepts/lstm.md
    - Loss Function: E_statistical_concepts/loss_function.md
    - Mann-Whitney U Test: E_statistical_concepts/mann_whitney.md
    - Mean Absolute Error: E_statistical_concepts/mae.md
    - Mean Absolute Percentage Error: E_statistical_concepts/mape.md
    - Mean Squared Error: E_statistical_concepts/mse.md
    - Mean Squared Logarithmic Error: E_statistical_concepts/msle.md
    - Multicollinearity: E_statistical_concepts/multicollinearity.md
    - Natural Language Processing (NLP): E_statistical_concepts/nlp.md
    - Neural Networks: E_statistical_concepts/neural_networks.md
    - Normalization: E_statistical_concepts/normalization.md
    - Optimization: E_statistical_concepts/optimization.md
    - Outliers: E_statistical_concepts/outliers.md
    - Overfitting: E_statistical_concepts/overfitting.md
    - PCA: E_statistical_concepts/pca.md
    - PDP: E_statistical_concepts/pdp.md
    - Permutation Importance: E_statistical_concepts/permutation_importance.md
    - Precison: E_statistical_concepts/precision.md
    - Precision-Recall Curve: E_statistical_concepts/precision_recall_curve.md
    - Pseudo R²: E_statistical_concepts/pseudo_r_squared.md
    - R² - Coefficient of Determination: E_statistical_concepts/r_squared.md
    - R² Adjusted: E_statistical_concepts/r_squared_adjusted.md
    - Random Forest: E_statistical_concepts/random_forest.md
    - Recall: E_statistical_concepts/recall.md
    - Recurrent Neural Networks (RNN): E_statistical_concepts/rnn.md
    - Regression: E_statistical_concepts/regression.md
    - ROC Curve: E_statistical_concepts/roc_curve.md
    - Root Mean Squared Error: E_statistical_concepts/rmse.md
    - Sampling: E_statistical_concepts/sampling.md  
    - Seasonality: E_statistical_concepts/seasonality.md
    - SHAP: E_statistical_concepts/shap.md
    - Skewness: E_statistical_concepts/skewness.md
    - Sobol: E_statistical_concepts/sobol.md
    - Specificity: E_statistical_concepts/specificity.md
    - Standard Deviation: E_statistical_concepts/standard_deviation.md
    - Standardization: E_statistical_concepts/standardization.md
    - Stationarity: E_statistical_concepts/stationarity.md
    - Transformers: E_statistical_concepts/transformers.md
    - Trend: E_statistical_concepts/trend.md
    - Variance: E_statistical_concepts/variance.md
    - Variance Inflation Factor: E_statistical_concepts/vif.md
    - Volatility: E_statistical_concepts/volatility.md
    - Wasserstein Distance: E_statistical_concepts/wasserstein_distance.md
    - Weight of Evidence: E_statistical_concepts/woe.md
  
  - Engineering Concepts:
    - Containerization: F_engineering_concepts/containerization.md
    - Data Engineering: F_engineering_concepts/data_engineering.md
    - Data Quality: F_engineering_concepts/data_quality.md
    - Data Versioning: F_engineering_concepts/data_versioning.md
    - Data Warehouse: F_engineering_concepts/data_warehouse.md
    - Data Lake: F_engineering_concepts/data_lake.md
    - DBT: F_engineering_concepts/dbt.md
    - ETL: F_engineering_concepts/etl.md
    - Feature Store: F_engineering_concepts/feature_store.md
    - Kubernetes: F_engineering_concepts/kubernetes.md
    - MLOps: F_engineering_concepts/mlops.md
    - Pipeline Orchestration: F_engineering_concepts/pipeline_orchestration.md
    - RAG: F_engineering_concepts/rag.md
    - Roles: F_engineering_concepts/roles.md
    - Virtual Private Network (VPN): F_engineering_concepts/vpn.md

  - Glossary:
      - 💰 Bank Context:
          - Approval Rating: G_glossary/bank_context/approval_rating.md
          - BNPL: G_glossary/bank_context/bnpl.md
          - Churn: G_glossary/bank_context/churn.md
          - CAC: G_glossary/bank_context/cac.md
          - COGS: G_glossary/bank_context/cogs.md
          - Credit Cycle: G_glossary/bank_context/credit_cycle.md
          - CSI: G_glossary/bank_context/csi.md
          - CTS: G_glossary/bank_context/cts.md
          - EAD: G_glossary/bank_context/ead.md
          - EBIT: G_glossary/bank_context/ebit.md
          - ECL: G_glossary/bank_context/ecl.md
          - FGC: G_glossary/bank_context/fgc.md
          - Float: G_glossary/bank_context/float.md
          - FPD: G_glossary/bank_context/fpd.md
          - IFRS9: G_glossary/bank_context/ifrs9.md
          - Indice de Basileia: G_glossary/bank_context/indice_basileia.md
          - Is Delayed: G_glossary/bank_context/is_delayed.md
          - KPI: G_glossary/bank_context/kpi.md
          - KS: G_glossary/bank_context/ks.md
          - LGD: G_glossary/bank_context/lgd.md
          - LTV: G_glossary/bank_context/ltv.md
          - NPL: G_glossary/bank_context/npl.md
          - PD: G_glossary/bank_context/pd.md
          - PDD: G_glossary/bank_context/pdd.md
          - Receivables Assignment: G_glossary/bank_context/receivables_assignment.md
          - Revolving Credit: G_glossary/bank_context/revolving_credit.md
          - ROE: G_glossary/bank_context/roe.md
          - ROI: G_glossary/bank_context/roi.md
          - SLA: G_glossary/bank_context/sla.md
          - Stop Accrual: G_glossary/bank_context/stop_accrual.md
          - Supply Chain: G_glossary/bank_context/supply.md
          - TPV: G_glossary/bank_context/tpv.md

      - 🕵️‍♂️ Fraud Context:       
        - Fraud Prevention: G_glossary/fraud_context/fraud_prevention.md
        - Fraud Risk Management: G_glossary/fraud_context/fraud_risk_management.md
        - Fraudulent Transaction: G_glossary/fraud_context/fraudulent_transaction.md
        - KYC: G_glossary/fraud_context/kyc.md
        - Money Laundering: G_glossary/fraud_context/money_laundering.md
        - Suspicious Activity: G_glossary/fraud_context/suspicious_activity.md

  - Tutorials:
    - Airflow: H_tutorials/airflow.md
    - APIs: H_tutorials/apis.md
    - AWS: H_tutorials/aws.md
    - Cloud Computing: H_tutorials/cloud_computing.md
    - Data Visualization: H_tutorials/data_viz.md
    - Docker: H_tutorials/docker.md
    - GCP: H_tutorials/gcp.md
    - Git and GitHub: H_tutorials/git_github.md
    - Looker: H_tutorials/looker.md
    - Python: 
      - Pycaret: H_tutorials/python/pycaret.md
    - R: 
      - H_tutorials/R/r_base.md
    - SQL: H_tutorials/sql.md
    - Streamlit: H_tutorials/streamlit.md
    - Tableau: H_tutorials/tableau.md
    - VS Code: H_tutorials/vs_code.md

  - Projects:
    - Crime California (Shiny App): I_projects/crime_california.md
    - Distributions Comparison: I_projects/distributions_comparison.md
    - Fraud Detection: I_projects/fraud_detection.md
  
  - Presentations:
    - 📊 Data Science: J_presentations/data_science.md
    - 📈 Machine Learning: J_presentations/machine_learning.md
    - 🧠 Deep Learning: J_presentations/deep_learning.md
    - 🕸️ Graphs: J_presentations/graphs.md
    - 📚 Statistics: J_presentations/statistics.md
    - 🛠️ Tools and Technologies: J_presentations/tools_and_technologies.md

  - Study Notes: 
    - Teste: K_study_notes/study_notes.md
    - Optimization: 
      - Heuristical: K_study_notes/heuristical_optimization.md
      - Convex: K_study_notes/convex_optimization.md
    - Kanban: K_study_notes/kanban.md

  - Articles: L_articles/articles.md

  - Paradoxes: M_paradoxes/paradoxes.md

  - Links: N_links/links.md

  - References: O_references/references.md

theme:
  name: material
  features:
    #- navigation.expand        # Menus expansíveis
    - navigation.top           # Mostra o menu de navegação no topo também
    - navigation.instant       # Navegação sem recarregar a página
    - content.code.copy       # Botão de copiar código com um clique nos blocos de código
    - navigation.indexes  # Necessário para index.md funcionar automaticamente
  palette:
    - scheme: default         # Light mode
      primary: indigo
      accent: deep orange
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

    - scheme: slate           # Dark mode
      primary: indigo
      accent: deep orange
      toggle:
        icon: material/white-balance-sunny
        name: Switch to light mode


markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - tables
  - md_in_html # Necessário p/ Markdown (tabela) dentro de HTML

extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - js/mathjax-refresh.js

plugins:
  - search
  - mermaid2
